### ISSUE TITLE
Generation fails from source code

### ISSUE THREAD

**Issue by OpenSemi-de** [idexus/Sharp.UI#3]
Hey,

its me again.
Using the nuget package i was able to fix the first issues. now that you submitted some of the patches to the source repo i wanted to use this instead of the nuget package. 
while trying i noticed the there are no partial classes generated. do i have to setup anything more than referencing the source code?

i pushed the app as example to our repo

**Comment by idexus** [comment]
If you want to use the `Sharp.UI` library by project reference

```xml
<ItemGroup>
    <ProjectReference Include="..\Sharp.UI\Sharp.UI.csproj" />
    <ProjectReference Include="..\Sharp.UI.Generator\Sharp.UI.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
</ItemGroup>

**Comment by OpenSemi-de** [comment]
That did the trick. Thanks again
