### ISSUE TITLE
False errors in Visual Studio

### ISSUE THREAD

**Issue by OpenSemi-de** [idexus/Sharp.UI#4]
Hi there,

i'm using the latest source in VS 2022 (17.4.3) in our repo now.  There is still some issue with false errors. In the IDE i get 16 errors but the project compiles and runs fine. This is gettimg inconvienient because if theres a real error i have to search through the list. Any ideas?

Greetings,
Stephan

**Comment by idexus** [comment]
In my version of VS for Mac I only get warnings. It looks like you are creating a Layout property for example, but the generator generates a fluent Layout(..) helper method that hides the Layout method of the base class. Use more custom names when creating properties.

**Comment by OpenSemi-de** [comment]
Since you made some changes to the source this error is gone. I dont know what it was, but you fixed it
