### ISSUE TITLE
builder.CodeMarkupApp<App> - No accessible extension method

### ISSUE THREAD

**Issue by appsure** [idexus/Sharp.UI#49]
Hi idexus, starting a new Maui app project and can't resolve this.  CodeMarkup.Maui was included as a nuget along with HotReloadKit, no luck. 

the compile error:
'MauiAppBuilder' does not contain a definition for 'CodeMarkupApp' and no accessible extension method 'CodeMarkupApp' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)

My code in MauiProgram.cs:

using System;
using CommunityToolkit.Maui;

namespace ReloadTest
{
    using CodeMarkup.Maui;

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder.CodeMarkupApp<App>(HotReloadSupport.IdeIPs).UseMauiApp<App>().ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            }).UseMauiCommunityToolkit().UseMauiCommunityToolkitMediaElement();
            /*builder.Services.AddSingleton<ListViewPageViewModel>();
            builder.Services.AddSingleton<SecondPageViewModel>();
            builder.Services.AddSingleton<KeypadViewModel>();

            builder.Services.AddSingleton<ListViewPage>();
            builder.Services.AddSingleton<SecondPage>();
            builder.Services.AddSingleton<KeypadPage>();

            Routing.RegisterRoute("details", typeof(NavigationDetailPage));
            Routing.RegisterRoute("seconddetails", typeof(NavigationSecondDetailPage));*/
            return builder.Build();
        }
    }
}

**Comment by appsure** [comment]
@tcsaddul Yea I've tried that, no luck.  Any other ideas?  I'm using Visual Studio Mac.

**Comment by idexus** [comment]
try to use 0.5.1-alpha nuget package

**Comment by appsure** [comment]
Thanks for the update - fixed that issue.  Do I need to then manually add these lines to the csproj file?  Seems I'm not getting the autogenerated classes generated.

<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

	<ItemGroup>
	  <None Remove="Pages\Navigation\" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
	    <None Include="$(CompilerGeneratedFilesOutputPath)/CodeMarkup.Maui.Generator.Classes/**/*.cs" />
	    <None Include="$(CompilerGeneratedFilesOutputPath)/CodeMarkup.Maui.Generator.Extensions/**/*.cs" />
		<None Include="$(CompilerGeneratedFilesOutputPath)/HotReloadKit.Generator/**/*.cs" />
    </ItemGroup>

**Comment by idexus** [comment]
VS does not show generated files, if you are using VS for mac then yes, for VS for windows it is not necessary as you can see it in Analyzers tab

**Comment by appsure** [comment]
I was able to fire up the vanilla project with the new updates and it worked well.  Also integrated it into my current project as a single nuget and it works well.  **Is it possible to use a NavigationPage as the App MainPage instead of a Shell?**  If I do that, the reloading fails.  Either way, great tool here.  Thanks for releasing this!

**Comment by appsure** [comment]
Never mind, using the CodeMarkup.Maui.NavigationPage I was able to get the reload to work.  Only thing is there is now no constructor to set the RootPage on your NavigationPage.  I was able to just Push my RootPage, but not sure this is best practice.  Thanks.

**Comment by idexus** [comment]
I'm glad you like the project.

NavigationPage Example:

[https://github.com/idexus/CodeMarkup-Maui/blob/main/src/samples/ExampleApp/MainPages/FlyoutApp/FlyoutMainPage.cs](https://github.com/idexus/CodeMarkup-Maui/blob/main/src/samples/ExampleApp/MainPages/FlyoutApp/FlyoutMainPage.cs)

**Comment by appsure** [comment]
Makes sense - thanks again.  May I buy you a coffee?  Do you have a link?
