### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by crimer** [idexus/Sharp.UI#54]
Hello, I'm launching a project with the default configuration (F5 in JetBrains Rider) and a hot reload does not work.
```
        var builder = MauiApp.CreateBuilder();
        builder
            .CodeMarkupApp<App>(HotReloadSupport.IdeIPs)
            .UseMauiApp<App>()
```

How to launch a project correctly so that a hot reload works?

**Comment by idexus** [comment]
I do not have plans to support Rider. You can now use VS code

[VS code extension](https://github.com/idexus/HotReloadKit/releases/tag/0.5.0-beta.2)
