### ISSUE TITLE
Missing windows target

### ISSUE THREAD

**Issue by OpenSemi-de** [idexus/Sharp.UI#6]
Hello there,

could you enable the windows build target to the project file? I can't update the nuget package because it says:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Sharp.UI 0.2.4-alpha.1 is not compatible with net7.0-windows10.0.19041 (.NETCoreApp,Version=v7.0) / android-arm. Package Sharp.UI 0.2.4-alpha.1 supports:
  - net7.0-android33.0 (.NETCoreApp,Version=v7.0)
  - net7.0-ios16.1 (.NETCoreApp,Version=v7.0)
  - net7.0-maccatalyst16.1 (.NETCoreApp,Version=v7.0)	ACDCs	C:\Users\lmnt1\Desktop\OSSpice\ACDCs\ACDCs.csproj	1	

Thanks a lot and keep up the great work

Stephan

**Comment by idexus** [comment]
Hello,

Try new nuget package 0.2.5-alpha.1

**Comment by OpenSemi-de** [comment]
The new package was installed correctly. Thank you!
