### ISSUE TITLE
Ultrasonic Analyzer App

### ISSUE THREAD

**Issue by sebi5361** [idexus/Sharp.UI#63]
Dear idexus,

Please forgive me for being bold contacting you this way but I don't know another way to do it for free (through LinkedIn?).

I am considering to purchase your Ultrasonic Analyzer iOS app.
Can you confirm that the internal microphone in my iPhone 15 is good enough (roll-off ok?) to capture up to 50kHz ultrasounds? 

With kind regards,

Sébastien

**Comment by idexus** [comment]
Hello, 

For the analysis of sounds with frequencies up to 50kHz, you need to use an external microphone.

**Comment by sebi5361** [comment]
Thank you Pawel! Would you recommend a one in particular?
